spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    concurrency:
      min: 5
      max: 20
    queues:
      verification:
        queue: verification.queue
      notification:
        queue: notification.queue
statistics:
  logging:
    interval:
      minutes: 60
      initial:
        minutes: 3

logging:
  level:
    root: info
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} - %msg%n'