spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:know.how.12312@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    concurrency:
      min: 5
      max: 20
    queues:
      verification:
        queue: verification.queue
      notification:
        queue: notification.queue
statistics:
  logging:
    interval:
      minutes: 60
      initial:
        minutes: 3

email:
  subject:
    verification: Email Verification
    purchase: Course Purchase
    add_to_moderation: Course Add To Moderation
    review_result: Moderation result

logging:
  level:
    root: info
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} - %msg%n'