version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 6758
      POSTGRES_DB: know_how_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - general-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redispass123}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispass123}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - general-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass123}
      - REDIS_PORT=6379
      - REDIS_HOST=localhost

  core-service:
    image: slavyanin30/know_how:latest
    container_name: core-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/know_how_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 6758
    networks:
      - general-network

  notification-service:
    image: slavyanin30/know_how_notification:latest
    container_name: notification-service
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin123
      MAIL_USERNAME: know.how.12312@gmail.com
      MAIL_PASSWORD: gxigfstxhxvndvtq
    networks:
      - general-network

networks:
  general-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: