spring:
  application:
    name: core-service
    rest:
      api:
        prefix: /api
  datasource:
    url: jdbc:postgresql://localhost:5436/know_how_db
    username: user
    password: 6758
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: false
    baseline-version: 1
    baseline-on-migrate: true
    loggers: slf4j
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        transaction:
          jta:
            platform: none
    database: postgresql
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    connection-timeout: 5000
    publisher-confirm-type: correlated
    publisher-returns: true
    confirms:
      statistic:
        log:
          delay:
            min:
              fixed: 10
              initial: 5
    notification-service:
      exchange: main.direct.exchange
      queues:
        verification:
          queue: verification.queue
          ttl: 180000
          key: verification.key
        notification:
          queue: notification.queue
          key: notification.key
  retry-template:
    max-retry: 3
    back-off:
      jitter: 300
      interval:
        init: 1000
        max: 5000
      multiplier: 1.5


server:
  port: 8080
  base-url:
    auth: /api/v1/auth
    profile: /api/v1/profile
    users: /api/v1/users
    course: /api/v1/courses
    balance: /api/v1/balance
    tag: /api/v1/tags


csrf:
  token:
    header-name: X-CSRF-TOKEN

jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

moderator:
  code: 'Sqwe414jmgjdgsrf32!.o;o24f'

coins:
  start-amount: 100

frontend:
  base:
    url: http://localhost:5173

logging:
  level:
    root: info
    org.springframework.security: debug
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} - %msg%n'

course:
  price-multiplier: 20